Repository Wingle-SMWU/Wingle-Backend, pull requests merged in 2023-02, with the labels that each got.

#13 Feat/mock mvc 세팅 #11
  wingle/src/main/java/kr/co/wingle/common/dto/ApiResponse.java
  wingle/src/test/java/kr/co/wingle/hello/HelloControllerTest.java
Labels: enhancement

#19 [chore] JaCoCo 제외 대상 설정 #18
  wingle/build.gradle
  wingle/lombok.config
Labels: enhancement

#25 [feat] S3 설정
  wingle/build.gradle
  wingle/src/main/java/kr/co/wingle/common/config/AmazonS3Config.java
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/util/S3Util.java
Labels: enhancement

#30 [feat] 회원가입 기능 구현
  wingle/build.gradle
  wingle/src/main/java/kr/co/wingle/common/config/JwtSecurityConfig.java
  wingle/src/main/java/kr/co/wingle/common/config/SecurityConfig.java
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/dto/TokenDto.java
  wingle/src/main/java/kr/co/wingle/common/exception/RestExceptionHandler.java
  wingle/src/main/java/kr/co/wingle/common/jwt/JwtAccessDeniedHandler.java
  wingle/src/main/java/kr/co/wingle/common/jwt/JwtAuthenticationEntryPoint.java
  wingle/src/main/java/kr/co/wingle/common/jwt/JwtFilter.java
  wingle/src/main/java/kr/co/wingle/common/jwt/TokenInfo.java
  wingle/src/main/java/kr/co/wingle/common/jwt/TokenProvider.java
  wingle/src/main/java/kr/co/wingle/common/util/SecurityUtil.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/MemberRepository.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupResponseDto.java
  wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/AuthServiceTest.java
  wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
  wingle/src/test/resources/images/testImage.png
Labels: enhancement

#35 [bug] deploy.yml 빌드 오류
  .github/workflows/deploy.yml
  wingle/build.gradle
  wingle/src/main/java/kr/co/wingle/common/config/RedisConfig.java
  wingle/src/main/java/kr/co/wingle/common/config/RestTemplateConfig.java
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/common/exception/RestExceptionHandler.java
  wingle/src/main/java/kr/co/wingle/common/jwt/JwtAuthenticationEntryPoint.java
  wingle/src/main/java/kr/co/wingle/common/jwt/JwtFilter.java
  wingle/src/main/java/kr/co/wingle/common/jwt/TokenInfo.java
  wingle/src/main/java/kr/co/wingle/common/jwt/TokenProvider.java
  wingle/src/main/java/kr/co/wingle/common/util/RedisUtil.java
  wingle/src/main/java/kr/co/wingle/common/util/SecurityUtil.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/CustomUserDetailsService.java
  wingle/src/main/java/kr/co/wingle/member/Term.java
  wingle/src/main/java/kr/co/wingle/member/TermMember.java
  wingle/src/main/java/kr/co/wingle/member/dto/LoginRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/MemberResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/TokenDto.java
  wingle/src/test/java/kr/co/wingle/hello/HelloControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/AuthServiceTest.java
  wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
Labels: bug

#33 [feat] 로그인 기능 구현
  .github/workflows/deploy.yml
  wingle/src/main/java/kr/co/wingle/member/AuthService.java
  wingle/src/test/java/kr/co/wingle/member/AuthServiceTest.java
Labels: enhancement

#41 [fix] SecuriyConfig url 추가 #40
  wingle/src/main/java/kr/co/wingle/common/config/SecurityConfig.java
Labels: bug

#49 [Breaking change] RedisConfig 수정
  wingle/src/main/java/kr/co/wingle/common/config/RedisConfig.java
  wingle/src/main/java/kr/co/wingle/common/util/RedisUtil.java
Labels: enhancement

#45 Feat/ 인증 번호 전송하기 #44
  wingle/build.gradle
  wingle/src/main/java/kr/co/wingle/common/config/MailConfig.java
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/MailService.java
  wingle/src/main/java/kr/co/wingle/member/dto/EmailRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/EmailResponseDto.java
  wingle/src/main/resources/templates/mail.html
  wingle/src/test/java/kr/co/wingle/member/AuthServiceTest.java
Labels: enhancement

#55 [refactor] member 폴더 구조 정리
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/MemberRepository.java
  wingle/src/main/java/kr/co/wingle/member/dto/MemberResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/entity/Authority.java
  wingle/src/main/java/kr/co/wingle/member/entity/Member.java
  wingle/src/main/java/kr/co/wingle/member/entity/Permission.java
  wingle/src/main/java/kr/co/wingle/member/entity/Term.java
  wingle/src/main/java/kr/co/wingle/member/entity/TermMember.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/service/CustomUserDetailsService.java
  wingle/src/main/java/kr/co/wingle/member/service/MailService.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
  wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/AuthServiceTest.java
  wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
Labels: refactor

#52 [feat] 로그아웃 API
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/jwt/JwtFilter.java
  wingle/src/main/java/kr/co/wingle/common/jwt/TokenProvider.java
  wingle/src/main/java/kr/co/wingle/common/util/RedisUtil.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/dto/LogoutRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
Labels: enhancement

#50 Feat/인증 번호 확인하기 #47
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/dto/CertificationRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/CertificationResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
Labels: enhancement

#57 [feat] 수락 대기 목록 조회 API
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/common/exception/ForbiddenException.java
  wingle/src/main/java/kr/co/wingle/common/exception/RestExceptionHandler.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/MemberRepository.java
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingListResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
  wingle/src/main/java/kr/co/wingle/profile/Profile.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileRepository.java
  wingle/src/test/java/kr/co/wingle/member/MemberControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
  wingle/src/test/java/kr/co/wingle/member/service/MemberServiceTest.java
Labels: enhancement

#60 Feat/회원가입 수락 전송하기 #59
  wingle/src/main/java/kr/co/wingle/common/config/MailConfig.java
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/dto/AcceptanceRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/AcceptanceResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/mailVo/AcceptanceMail.java
  wingle/src/main/java/kr/co/wingle/member/mailVo/CodeMail.java
  wingle/src/main/java/kr/co/wingle/member/mailVo/Mail.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/service/MailService.java
  wingle/src/main/resources/templates/acceptance.html
  wingle/src/main/resources/templates/code.html
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
Labels: enhancement

#63 [feat] 회원가입 API 수정
  wingle/src/main/java/kr/co/wingle/member/TermMemberRepository.java
  wingle/src/main/java/kr/co/wingle/member/TermRepository.java
  wingle/src/main/java/kr/co/wingle/member/dto/LoginRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/entity/Term.java
  wingle/src/main/java/kr/co/wingle/member/entity/TermCode.java
  wingle/src/main/java/kr/co/wingle/member/entity/TermMember.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
  wingle/src/main/java/kr/co/wingle/profile/Profile.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileRepository.java
  wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
Labels: enhancement

#64 [Breaking change] 로그인 API 수정
  wingle/src/main/java/kr/co/wingle/member/dto/TokenDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
Labels: enhancement

#69 [refactor] 토큰 응답 수정
  wingle/src/main/java/kr/co/wingle/common/jwt/TokenProvider.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/dto/LoginResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/TokenDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
Labels: refactor

#43 Feat/닉네임 중복 확인하기 #39
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/dto/NicknameRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/NicknameResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/profile/Profile.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileRepository.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
Labels: enhancement

#71 [feat] 수락 대기 사용자 조회 API
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
  wingle/src/test/java/kr/co/wingle/member/MemberControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/service/MemberServiceTest.java
Labels: enhancement

#74 [feat] 수락 거절,완료 목록 조회
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/MemberRepository.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingListResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
  wingle/src/test/java/kr/co/wingle/member/MemberControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
  wingle/src/test/java/kr/co/wingle/member/service/MemberServiceTest.java
Labels: enhancement

#77 [refactor] 프로필 nation 엔티티 제거
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/profile/Language.java
  wingle/src/main/java/kr/co/wingle/profile/MemberLanguage.java
  wingle/src/main/java/kr/co/wingle/profile/MemberSns.java
  wingle/src/main/java/kr/co/wingle/profile/Nation.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileRepository.java
  wingle/src/main/java/kr/co/wingle/profile/entity/Interest.java
  wingle/src/main/java/kr/co/wingle/profile/entity/Language.java
  wingle/src/main/java/kr/co/wingle/profile/entity/MemberInterest.java
  wingle/src/main/java/kr/co/wingle/profile/entity/Profile.java
  wingle/src/main/java/kr/co/wingle/profile/entity/Sns.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
  wingle/src/test/java/kr/co/wingle/member/service/MemberServiceTest.java
Labels: refactor
