Repository Wingle-SMWU/Wingle-Backend, pull requests merged in 2023-08, with the labels that each got.

#254 [fix] AES256Util iv, key application.yml 값으로 변경 및 salt 추가
  .github/workflows/deploy.yml
  wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java
Labels: enhancement

#262 Fix/익명게시판 사용자 구분 #224
  wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java
  wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
  wingle/src/main/java/kr/co/wingle/community/util/ProcessedPersonalInformation.java
Labels: bug, enhancement

#265 Feat/안 읽은 쪽지 개수 추가 #264
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/message/controller/MessageController.java
  wingle/src/main/java/kr/co/wingle/message/dto/RoomResponseDto.java
  wingle/src/main/java/kr/co/wingle/message/dto/UnreadMessageCountResponseDto.java
  wingle/src/main/java/kr/co/wingle/message/entity/RoomMember.java
  wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
  wingle/src/main/java/kr/co/wingle/message/service/RoomService.java
Labels: enhancement

#267 [fix] 탈퇴한 유저의 자유게시판 글 조회 시 닉네임 (알수없음)으로 수정
  wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
Labels: enhancement

#270 [fix] 복호화 시 Hex decode 하도록 수정
  wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java
Labels: bug

#271 [merge] 오류 수정사항 test 브랜치에 머지
  wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java
  wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
Labels: bug, enhancement

#272 [merge] 수정사항 test 브랜치에 머지
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleController.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
Labels: enhancement
