Repository Wingle-SMWU/Wingle-Backend, pull requests merged in 2023-06, with the labels that each got.

#164 [Refactor] admin userId 암호화 #161
  wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/dto/PermissionResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
Labels: refactor

#167 [fix] 게시글, 댓글 최대글자수 수정
  wingle/src/main/java/kr/co/wingle/community/article/ArticleRequestDto.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java
  wingle/src/main/java/kr/co/wingle/writing/Writing.java
Labels: enhancement

#168 Fix/커뮤니티 정렬 수정 #160
  wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentService.java
Labels: enhancement

#170 [add] 인증코드 전송 시 이메일 중복처리 추가
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
Labels: enhancement

#171 [add] 에러 확인을 위한 프린트문 추가
  wingle/src/main/java/kr/co/wingle/member/service/MailService.java
Labels: bug

#172 [del] 프린트문 삭제
  wingle/src/main/java/kr/co/wingle/member/service/MailService.java
Labels: refactor

#151 Refactor/user key 암호화 #150
  wingle/build.gradle
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/dto/PermissionResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileController.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
Labels: refactor

#177 feat: allowedOrigins 에 admin 페이지 추가 #176
  wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
Labels: enhancement

#179 allowedOrigins에 web 페이지 추가 # 178
  wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
Labels: enhancement
