Repository Wingle-SMWU/Wingle-Backend, pull requests merged in 2023-04, with the labels that each got.

#101 [refactor] 로그 내용 수정
  wingle/src/main/java/kr/co/wingle/common/aop/LogAspect.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
Labels: refactor

#102 Feat/cors 문제 해결 #94
  wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
Labels: enhancement

#103 [feat] 로컬호스트 허용 포트 추가 #94
  wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
Labels: enhancement

#107 [fix] 게시글 목록 보기 경로 수정 #104
  wingle/src/main/java/kr/co/wingle/community/article/ArticleController.java
Labels: bug, enhancement

#109 Feat/관리자 페이지네이션 사이즈 조정 #108
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
Labels: enhancement

#113 [feat] CORS 허용 http 메서드 추가 #94
  wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
Labels: enhancement

#90 [feat] profile/detail-API-#89
  wingle/src/main/java/kr/co/wingle/profile/ProfileController.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
  wingle/src/main/java/kr/co/wingle/profile/SnsRepository.java
  wingle/src/main/java/kr/co/wingle/profile/dto/ProfileViewResponseDto.java
Labels: enhancement

#116 Feat/어드민 회원 메모 #111
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/dto/MemoRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/MemoResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/entity/Member.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
Labels: enhancement

#117 Feat/어드민 회원가입 거절사유 #110
  wingle/build.gradle
  wingle/src/docs/asciidoc/community/forum/forumApi.adoc
  wingle/src/docs/asciidoc/index.adoc
  wingle/src/main/java/kr/co/wingle/common/config/SecurityConfig.java
  wingle/src/test/java/kr/co/wingle/community/forum/ForumControllerTest.java
  wingle/src/test/java/kr/co/wingle/util/ControllerTest.java
  wingle/src/test/java/kr/co/wingle/util/RestDocsConfig.java
  wingle/src/test/java/kr/co/wingle/util/RestDocsTestSupport.java
  wingle/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  wingle/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  wingle/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: enhancement

#120 [fix] 메시지 없는 쪽지방 조회 가능하게 수정#119
  wingle/src/main/java/kr/co/wingle/message/dto/RoomResponseDto.java
Labels: bug

#122 [fix] 쪽지 없는 경우 에러 처리 #121
  wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
Labels: bug

#124 [feat] 쪽지 목록 역순 정렬 #123
  wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseDto.java
  wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
Labels: enhancement

#127 [fix] Long 비교 연산자 수정
  wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentService.java
Labels: bug
