Repository Wingle-SMWU/Wingle-Backend, pull requests merged in 2023-07, with the labels that each got.

#196 [feat] 쪽지 내역 조회에 UserID 추가 # 195
  wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseWithRecipentDto.java
  wingle/src/main/java/kr/co/wingle/message/dto/RoomMemberDto.java
  wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
  wingle/src/main/java/kr/co/wingle/message/service/RoomService.java
Labels: enhancement

#198 [fix] 인증코드 유효시간 3분에서 5분으로 수정
  wingle/src/main/java/kr/co/wingle/member/mailVo/CodeMail.java
Labels: enhancement

#199 [fix] 게시글, 댓글 최대글자수 변경 및 글자수 validator 수정
  wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscape.java
  wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscapeValidator.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleRequestDto.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java
Labels: enhancement

#200 [fix] validator 수정
  wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscapeValidator.java
Labels: bug, enhancement

#201 [fix] validator 수정
  wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscapeValidator.java
Labels: enhancement

#202 [fix] validator 수정 및 게시글 최대 3000자로 변경
  wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscapeValidator.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleRequestDto.java
Labels: bug

#193 [fix] 승인된 유저만 로그인 허용 #188
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
Labels: bug

#205 [fix] nickname 형식 유효검사 수정 (한글/영문/숫자 2-10자)
  wingle/src/main/java/kr/co/wingle/profile/dto/ProfileRequestDto.java
Labels: enhancement

#206 [fix] 사용가능언어 중복값 제거 후 저장
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
Labels: enhancement

#192 Fix/가입 거절된 회원 재가입 허용 #187
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/member/TermMemberRepository.java
  wingle/src/main/java/kr/co/wingle/member/entity/Member.java
  wingle/src/main/java/kr/co/wingle/member/entity/TermMember.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
  wingle/src/main/java/kr/co/wingle/profile/entity/Profile.java
  wingle/src/main/java/kr/co/wingle/profile/util/ProfileUtil.java
Labels: bug

#209 Fix/중복 이메일 res 수정 #208
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
Labels: bug, enhancement

#211 [fix] content length check validator 수정
  wingle/src/main/java/kr/co/wingle/common/validator/LengthWithoutCR.java
  wingle/src/main/java/kr/co/wingle/common/validator/LengthWithoutCRValidator.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleRequestDto.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java
Labels: bug

#214 [fix] CustomException http status별로 분리
  wingle/src/main/java/kr/co/wingle/common/exception/BadRequestException.java
  wingle/src/main/java/kr/co/wingle/common/exception/InternalServerErrorException.java
  wingle/src/main/java/kr/co/wingle/common/exception/RestExceptionHandler.java
  wingle/src/main/java/kr/co/wingle/common/exception/UnauthorizedException.java
  wingle/src/main/java/kr/co/wingle/common/util/S3Util.java
  wingle/src/main/java/kr/co/wingle/common/util/SecurityUtil.java
  wingle/src/main/java/kr/co/wingle/common/util/StringUtil.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/service/MailService.java
Labels: enhancement

#216 [fix] 자기소개 request 글자수 제한 수정
  wingle/src/main/java/kr/co/wingle/profile/dto/IntroductionRequestDto.java
Labels: enhancement

#220 [feat] 누락된 userId 암호화 반영
  wingle/build.gradle
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/dto/AcceptanceRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/MemoRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/PermissionResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/RejectionRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
  wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseWithRecipentDto.java
  wingle/src/main/java/kr/co/wingle/message/dto/RoomRequestDto.java
  wingle/src/main/java/kr/co/wingle/message/mapper/MessageMapper.java
  wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
  wingle/src/main/java/kr/co/wingle/message/service/RoomService.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileController.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
Labels: enhancement

#222 [fix] 공지게시판 작성자 이름 변경
  wingle/src/main/java/kr/co/wingle/community/forum/ForumService.java
Labels: enhancement

#223 Feat/회원가입 학교 학과 학번 추가 #218
  wingle/src/main/java/kr/co/wingle/affliation/controller/AffliationController.java
  wingle/src/main/java/kr/co/wingle/affliation/dto/SchoolResponseDto.java
  wingle/src/main/java/kr/co/wingle/affliation/entity/School.java
  wingle/src/main/java/kr/co/wingle/affliation/repository/SchoolRepository.java
  wingle/src/main/java/kr/co/wingle/affliation/service/SchoolService.java
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/entity/Member.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
  wingle/src/test/java/kr/co/wingle/member/service/MemberServiceTest.java
Labels: enhancement

#225 Feat/학생증 업로드 #213
  wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java
  wingle/src/main/java/kr/co/wingle/common/util/S3Util.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/dto/IdCardImageReqeustDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/IdCardImageResponseDto.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
Labels: enhancement

#227 Add/커뮤니티 res 대학명 추가 #226
  wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentResponseDto.java
  wingle/src/main/java/kr/co/wingle/community/forum/ForumService.java
  wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
  wingle/src/main/java/kr/co/wingle/community/util/ProcessedPersonalInformation.java
Labels: enhancement

#228 [fix] 커뮤니티 response 사용자 대학명 오류 수정
  wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
Labels: bug

#230 [feat] admin 사용자 상세조회에 학교, 학과, 학번 추가
  wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
Labels: enhancement

#232 [feature] 프로필, 쪽지 내역 조회 시 학교명 추가 #231
  wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseWithRecipentDto.java
  wingle/src/main/java/kr/co/wingle/message/dto/RoomMemberDto.java
  wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
  wingle/src/main/java/kr/co/wingle/message/service/RoomService.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
  wingle/src/main/java/kr/co/wingle/profile/dto/ProfileGetResponseDto.java
Labels: enhancement

#235 [feat] admin 리스트 조회 시 전체 유저수 조회
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/MemberRepository.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseWithPagesDto.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
Labels: enhancement

#238 Feat/이메일 반응형 #237
  wingle/src/main/java/kr/co/wingle/member/dto/SignupResponseDto.java
  wingle/src/main/resources/templates/acceptance.html
  wingle/src/main/resources/templates/apply.html
  wingle/src/main/resources/templates/code.html
  wingle/src/main/resources/templates/rejection.html
Labels: enhancement

#240 [fix] 익명게시판 외국윙그리 한국윙그리 구분 국적값 변경 (code->enNation)
  wingle/src/main/java/kr/co/wingle/community/forum/ForumService.java
Labels: enhancement

#242 [add] 리스트 조회 시 상태, 상태에 따른 일자, 학교이름 정보 추가
  wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseDto.java
Labels: enhancement

#244 [feat] 회원가입 시 학교 코드 받기 추가 #243
  wingle/src/main/java/kr/co/wingle/affliation/repository/SchoolRepository.java
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
Labels: enhancement

#246 [fix] 사용언어 리스트 순서 오류
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
Labels: bug

#248 [add] 프로필 상세조회 response에 학교명 추가
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
  wingle/src/main/java/kr/co/wingle/profile/dto/ProfileViewResponseDto.java
Labels: enhancement

#250 Feat/영문 이메일 #249
  wingle/src/main/java/kr/co/wingle/member/mailVo/AcceptanceMail.java
  wingle/src/main/java/kr/co/wingle/member/mailVo/ApplyMail.java
  wingle/src/main/java/kr/co/wingle/member/mailVo/Mail.java
  wingle/src/main/java/kr/co/wingle/member/mailVo/RejectionMail.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/profile/entity/Nation.java
  wingle/src/main/java/kr/co/wingle/profile/util/ProfileUtil.java
  wingle/src/main/resources/templates/acceptanceEn.html
  wingle/src/main/resources/templates/applyEn.html
  wingle/src/main/resources/templates/rejectionEn.html
Labels: enhancement
