Repository Wingle-SMWU/Wingle-Backend, pull requests merged in 2023-05, with the labels that each got.

#130 [add] 게시글 & 댓글 res에 userImage 추가
  wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java
Labels: enhancement

#133 Fix/미승인 유저 접근 비허용 #128
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentService.java
  wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
  wingle/src/main/java/kr/co/wingle/member/AuthController.java
  wingle/src/main/java/kr/co/wingle/member/MemberController.java
  wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
  wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
  wingle/src/main/java/kr/co/wingle/message/service/RoomService.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
  wingle/src/main/java/kr/co/wingle/writing/WritingService.java
  wingle/src/main/java/kr/co/wingle/writing/WritingUtil.java
  wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/MemberControllerTest.java
  wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
Labels: enhancement

#135 [fix] 관리자도 컨텐츠 접근가능하게 수정 #128
  wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
Labels: bug

#136 [refactor] CloudWatch로의 로그 전송 환경 세팅 #136
  wingle/build.gradle
  wingle/src/main/resources/logback-spring.xml
  wingle/src/main/resources/logback.xml
Labels: refactor

#140 [feat] 타인-프로필-조회 #139
  wingle/src/main/java/kr/co/wingle/profile/ProfileController.java
  wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
Labels: enhancement

#143 [fix] 쪽지 createdTime 비교 로직 수정 #142
  wingle/src/main/java/kr/co/wingle/message/dto/RoomResponseDto.java
Labels: bug

#141 Refactor/cloudWatch request, response 세팅 #136
  wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java
  wingle/src/main/java/kr/co/wingle/common/filter/ReadableRequestBodyWrapper.java
  wingle/src/main/java/kr/co/wingle/common/filter/ReadableResponseBodyWrapper.java
  wingle/src/main/resources/logback-spring.xml
  wingle/src/main/resources/logback.xml
Labels: refactor

#145 Refactor/Req, Res 로깅 추가 #136
  wingle/src/main/java/kr/co/wingle/common/aop/LogAspect.java
  wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java
  wingle/src/main/java/kr/co/wingle/common/filter/ReadableRequestBodyWrapper.java
  wingle/src/main/java/kr/co/wingle/common/filter/ReadableResponseBodyWrapper.java
  wingle/src/main/resources/logback-spring.xml
Labels: refactor

#149 [feature] recipient 프로필 이미지 추가, 내 자신의 닉네임 null처리 #144
  wingle/src/main/java/kr/co/wingle/message/controller/MessageController.java
  wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseWithRecipentDto.java
  wingle/src/main/java/kr/co/wingle/message/mapper/MessageMapper.java
  wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
Labels: enhancement

#152 Fix/ form-data request를 처리할 수 있도록 분기 추가
  wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java
Labels: bug

#157 [fix] null 방지 코드 추가 #156
  wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java
Labels: bug

#155 [refactor] 로깅에서 hello api 제외
  wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java
Labels: enhancement

#159 Fix/커뮤니티 멤버아이디 암호화 #158
  wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java
  wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java
  wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java
  wingle/src/main/java/kr/co/wingle/community/comment/CommentResponseDto.java
Labels: enhancement, refactor
